services:
  backendtest:
    container_name: backend-test
    build:
      context: .
      dockerfile: Dockerfile
      target: test
    volumes:
      - .:/code
    depends_on:
      - redis
    stdin_open: true
    tty: true
  redis:
    container_name: redis_test
    image: "redis:alpine"
    ports:
      - ${REDIS_PORT}:6379
